// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1j3BmthtsgO9ITi8vhb8uf_5e7XaXosM',
    appId: '1:664561721011:android:0da34212497f33a28e5ac6',
    messagingSenderId: '664561721011',
    projectId: 'mindforest-f87d4',
    storageBucket: 'mindforest-f87d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWCmmjiLjzo-CP8_SXhqvOaDWsrUglQNA',
    appId: '1:664561721011:ios:e43d03f07d368c0d8e5ac6',
    messagingSenderId: '664561721011',
    projectId: 'mindforest-f87d4',
    storageBucket: 'mindforest-f87d4.appspot.com',
    androidClientId: '664561721011-nn42u01p400vvcjfthqlokrbmgpimh0t.apps.googleusercontent.com',
    iosClientId: '664561721011-oc0esctfat3ckas7ae110n6d2qnq534g.apps.googleusercontent.com',
    iosBundleId: 'br.com.mindforest',
  );
}
